# -*- coding: utf-8 -*-
"""Enas Khaled Tharwat Abdallah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OfAu77B_vpq5ycI_ikil7C2_4WYvHkTp

**Import Libraries**
"""

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

from IPython.display import display

"""**Load Dataset**"""

df = pd.read_csv("aug_train.csv")

print("Dataset Shape:", df.shape)

display(df.head())

"""**Dataset Information**"""

print("Columns:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

print("Missing Values:")
display(df.isnull().sum().sort_values(ascending=False))

print("Number of Duplicates:", df.duplicated().sum())

print("Statistical Summary:")
display(df.describe(include="all").T)

"""**Data Cleaning**"""

# Remove duplicate rows
df = df.drop_duplicates()

# Remove ID column because it does not help prediction
if "enrollee_id" in df.columns:
    df = df.drop("enrollee_id", axis=1)

# Convert target column to numeric
if df["target"].dtype == "object":
    df["target"] = df["target"].map({
        "yes": 1,
        "no": 0
    })

# Remove rows where target is missing
df = df.dropna(subset=["target"])

print("Dataset shape after cleaning:", df.shape)

"""**Target Distribution**"""

plt.figure(figsize=(7,5))

sns.countplot(data=df, x="target")

plt.title("Candidate Job Change Distribution")
plt.xlabel("Target (0 = No Job Change, 1 = Job Change)")
plt.ylabel("Number of Candidates")

plt.show()

print("Target Distribution:")
display(df["target"].value_counts())

print("\nTarget Percentage:")
display(df["target"].value_counts(normalize=True) * 100)

"""**Exploratory Data Analysis – Numerical Features**"""

numerical_columns = df.select_dtypes(include=np.number).columns.tolist()

numerical_columns.remove("target")

for column in numerical_columns:

    plt.figure(figsize=(7,5))

    sns.histplot(
        data=df,
        x=column,
        kde=True
    )

    plt.title(f"Distribution of {column}")
    plt.show()

"""**Exploratory Data Analysis – Categorical Features**"""

categorical_columns = df.select_dtypes(include="object").columns.tolist()

print("Categorical Features:")
print(categorical_columns)

for column in categorical_columns:

    plt.figure(figsize=(10,5))

    df[column].value_counts().head(10).plot(
        kind="bar"
    )

    plt.title(f"Top Categories in {column}")
    plt.xlabel(column)
    plt.ylabel("Count")

    plt.xticks(rotation=45)

    plt.show()

"""**Feature Engineering**"""

# Training hours groups

df["training_hours_group"] = pd.cut(
    df["training_hours"],
    bins=[-1, 20, 40, 60, 100, np.inf],
    labels=[
        "Low",
        "Medium",
        "High",
        "Very High",
        "Extreme"
    ]
)

"""**Experience conversion**"""

def convert_experience(value):

    if pd.isna(value):
        return np.nan

    value = str(value).strip()

    if value == "<1":
        return 0

    if value == ">20":
        return 21

    try:
        return float(value)
    except:
        return np.nan


df["experience_years_approx"] = df["experience"].apply(
    convert_experience
)

"""**Experience groups**"""

df["experience_group"] = pd.cut(
    df["experience_years_approx"],
    bins=[-1, 2, 5, 10, 15, np.inf],
    labels=[
        "0-2 Years",
        "3-5 Years",
        "6-10 Years",
        "11-15 Years",
        "15+ Years"
    ]
)

"""**Interaction**"""

df["training_experience_interaction"] = (
    df["training_hours"] *
    df["experience_years_approx"]
)

display(df.head())

"""**Training Hours**"""

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="target",
    y="training_hours"
)

plt.title("Training Hours vs Job Change")
plt.xlabel("Target")
plt.ylabel("Training Hours")

plt.show()

"""**Prepare Features and Target**"""

X = df.drop("target", axis=1)
y = df["target"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

"""**Identify Numerical and Categorical Columns**"""

numeric_features = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X.select_dtypes(
    include=["object", "category"]
).columns.tolist()

print("Numerical Features:")
print(numeric_features)

print("\nCategorical Features:")
print(categorical_features)

"""**Train/Test Split**"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

"""**Data Transformation**"""

numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_transformer,
            numeric_features
        ),
        (
            "cat",
            categorical_transformer,
            categorical_features
        )
    ]
)

"""**Logistic Regression Model**"""

logistic_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            LogisticRegression(
                max_iter=1000,
                class_weight="balanced"
            )
        )
    ]
)

logistic_model.fit(X_train, y_train)

logistic_predictions = logistic_model.predict(X_test)

"""**Random Forest Model**"""

random_forest_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            RandomForestClassifier(
                n_estimators=300,
                random_state=42,
                class_weight="balanced",
                n_jobs=-1
            )
        )
    ]
)

random_forest_model.fit(X_train, y_train)

rf_predictions = random_forest_model.predict(X_test)

"""**Model Evaluation Function**"""

def evaluate_model(model_name, y_true, predictions):

    accuracy = accuracy_score(
        y_true,
        predictions
    )

    precision = precision_score(
        y_true,
        predictions
    )

    recall = recall_score(
        y_true,
        predictions
    )

    f1 = f1_score(
        y_true,
        predictions
    )

    print("=" * 50)
    print(model_name)
    print("=" * 50)

    print("Accuracy :", round(accuracy, 4))
    print("Precision:", round(precision, 4))
    print("Recall   :", round(recall, 4))
    print("F1 Score :", round(f1, 4))

    print("\nClassification Report:")
    print(
        classification_report(
            y_true,
            predictions
        )
    )

    return {
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1
    }

"""**Evaluate Logistic Regression**"""

logistic_results = evaluate_model(
    "Logistic Regression",
    y_test,
    logistic_predictions
)

"""**Evaluate Random Forest**"""

rf_results = evaluate_model(
    "Random Forest",
    y_test,
    rf_predictions
)

"""**Confusion Matrix – Logistic Regression**"""

cm_logistic = confusion_matrix(
    y_test,
    logistic_predictions
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm_logistic,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title("Logistic Regression Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

"""**Confusion Matrix – Random Forest**"""

cm_rf = confusion_matrix(
    y_test,
    rf_predictions
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm_rf,
    annot=True,
    fmt="d",
    cmap="Greens"
)

plt.title("Random Forest Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

"""**Model Comparison**"""

results = pd.DataFrame([
    logistic_results,
    rf_results
])

display(results)


results.set_index("Model").plot(
    kind="bar",
    figsize=(10,6)
)

plt.title("Model Performance Comparison")
plt.ylabel("Score")
plt.ylim(0,1)

plt.xticks(rotation=0)

plt.show()

"""**Random Forest Feature Importance**"""

# Get the trained Random Forest model
rf_classifier = random_forest_model.named_steps["model"]

# Get transformed feature names
feature_names = (
    random_forest_model
    .named_steps["preprocessor"]
    .get_feature_names_out()
)

# Feature importance
feature_importance = pd.Series(
    rf_classifier.feature_importances_,
    index=feature_names
).sort_values(ascending=False)


plt.figure(figsize=(10,8))

feature_importance.head(20).sort_values().plot(
    kind="barh"
)

plt.title("Top 20 Most Important Features")
plt.xlabel("Importance")

plt.show()

print("Top 20 Important Features:")

display(
    feature_importance.head(20)
)

"""**Recruitment Statistics**"""

total_candidates = len(df)

job_change_candidates = df["target"].sum()

no_change_candidates = (
    len(df) - job_change_candidates
)

job_change_rate = (
    job_change_candidates /
    total_candidates
) * 100

average_training_hours = (
    df["training_hours"].mean()
)

print("Recruitment Statistics")
print("=" * 40)

print(
    "Total Candidates:",
    total_candidates
)

print(
    "Candidates Likely to Change Job:",
    job_change_candidates
)

print(
    "Candidates Not Likely to Change Job:",
    no_change_candidates
)

print(
    "Job Change Rate:",
    round(job_change_rate, 2),
    "%"
)

print(
    "Average Training Hours:",
    round(average_training_hours, 2)
)

"""**Education Trends**"""

education_trend = pd.crosstab(
    df["education_level"],
    df["target"],
    normalize="index"
) * 100

display(education_trend)


education_trend.plot(
    kind="bar",
    figsize=(10,6)
)

plt.title("Job Change Rate by Education Level")
plt.ylabel("Percentage")
plt.xlabel("Education Level")

plt.xticks(rotation=45)

plt.show()

"""**Experience Trends**"""

experience_trend = pd.crosstab(
    df["experience_group"],
    df["target"],
    normalize="index"
) * 100

display(experience_trend)

experience_trend.plot(
    kind="bar",
    figsize=(10,6)
)

plt.title("Job Change Rate by Experience Group")
plt.ylabel("Percentage")
plt.xlabel("Experience Group")

plt.xticks(rotation=45)

plt.show()

"""**Company Type Trends**"""

if "company_type" in df.columns:

    company_trend = pd.crosstab(
        df["company_type"],
        df["target"],
        normalize="index"
    ) * 100

    display(company_trend)

    company_trend.plot(
        kind="bar",
        figsize=(10,6)
    )

    plt.title("Job Change Rate by Company Type")
    plt.ylabel("Percentage")
    plt.xlabel("Company Type")

    plt.xticks(rotation=45)

    plt.show()

"""**Candidate Ranking – Top 10**"""

# Predict probability of job change
rf_probabilities = random_forest_model.predict_proba(X_test)[:, 1]

ranking_df = X_test.copy()

ranking_df["Actual_Target"] = y_test.values

ranking_df["Job_Change_Probability"] = (
    rf_probabilities
)

ranking_df = ranking_df.sort_values(
    by="Job_Change_Probability",
    ascending=False
)

top_10_candidates = ranking_df.head(10)

display(top_10_candidates)

"""**Top 10 Candidate Probabilities**"""

plt.figure(figsize=(10,6))

plt.bar(
    range(1, 11),
    top_10_candidates["Job_Change_Probability"]
)

plt.title("Top 10 Candidates by Predicted Job Change Probability")

plt.xlabel("Candidate Rank")
plt.ylabel("Probability")

plt.xticks(range(1,11))

plt.show()

"""**Dashboard – Target Distribution**"""

plt.figure(figsize=(7,5))

sns.countplot(
    data=df,
    x="target"
)

plt.title("Candidate Screening Overview")
plt.xlabel("Job Change Target")
plt.ylabel("Number of Candidates")

plt.show()

"""**Dashboard – Model Performance**"""

dashboard_results = results.set_index("Model")

dashboard_results[
    ["Accuracy", "Precision", "Recall", "F1 Score"]
].plot(
    kind="bar",
    figsize=(10,6)
)

plt.title("Recruitment Model Performance")
plt.ylabel("Score")
plt.ylim(0,1)

plt.xticks(rotation=0)

plt.show()

"""**Dashboard – Important Hiring Factors**"""

plt.figure(figsize=(10,8))

feature_importance.head(15).sort_values().plot(
    kind="barh"
)

plt.title("Most Important Hiring Factors")
plt.xlabel("Importance")

plt.show()

"""**Dashboard – Training Hours**"""

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="target",
    y="training_hours"
)

plt.title("Training Hours by Recruitment Outcome")

plt.xlabel(
    "Target (0 = No Job Change, 1 = Job Change)"
)

plt.ylabel("Training Hours")

plt.show()

"""**Business Insights**"""

print("BUSINESS INSIGHTS")
print("=" * 60)

print("""
1. The model helps recruiters identify candidates who may be
   more likely to change jobs.

2. Candidate characteristics such as education, experience,
   company type, company size and relevant experience can
   provide useful recruitment insights.

3. Training hours can be analyzed as an important candidate
   profile factor.

4. Feature importance from the Random Forest model helps
   identify the variables that contribute most to prediction.

5. Candidate ranking can help recruiters prioritize candidates
   for further human review.

6. The system should support recruiters rather than replace
   human decision-making.
""")

"""**Final Results Table**"""

print("FINAL MODEL RESULTS")

display(
    results.style.format({
        "Accuracy": "{:.4f}",
        "Precision": "{:.4f}",
        "Recall": "{:.4f}",
        "F1 Score": "{:.4f}"
    })
)